import Head from 'next/head'
import Image from 'next/image'
import MainBanners from '@/components/banner/banners';
import { useEffect, useState } from "react";
import Slider from '@/components/slider/slider'
import {Make_A_Fetch_Request} from '@/components/request/makerequest';
import EmptySlider from '@/components/slider/emptyslider'
import { createClient } from "@supabase/supabase-js";
export default function Home() {
  var randomNumber = Math.floor(Math.random() * 4) + 1;
  const [banners,bannersvalue] = useState([]);
  const [recentuploaded,recentuploadedvalue] = useState([]);
  const [webseries,webseriesvalue] = useState([]);
  const [romantic,romanticvalue] = useState([]);
  const [action,actionvalue] = useState([]);
  const [comedy,comedyvalue] = useState([]);
  const [crime,crimevalue] = useState([]);
  const [drame,dramavalue] = useState([]);
  const [horror,horrorvalue] = useState([]);
  const [trailer,trailerdata] = useState([]);
  const [adventure,adventurevalue] = useState([]);
  const [adult,adultvalue] = useState([]);
  const start = 0;
  const end = 19;
  const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_KEY);
  const banner = async ()=>{
    let Arrdata = await supabase.from('Free-Netflix-Banner').select('*').eq('id',randomNumber);
    if(Arrdata.data){
      localStorage.setItem("HomePageBanners", JSON.stringify(Arrdata.data[0]));
      bannersvalue(Arrdata.data[0]);
    }
  }
  const data = async ()=>{    
    const fetchdat = await Make_A_Fetch_Request("MainCategory",['WebSeries', 'Movies'],start,end);
    localStorage.setItem("HomePageRecentUpload", JSON.stringify(fetchdat));
    recentuploadedvalue(fetchdat); 
    const fetchdat1 = await Make_A_Fetch_Request("MainCategory",['WebSeries'],start,end);
    localStorage.setItem("HomePageWebSeriesData", JSON.stringify(fetchdat1));
    webseriesvalue(fetchdat1);   
    const fetchdat2 = await Make_A_Fetch_Request("Geans",['Romantic'],start,end);
    localStorage.setItem("HomePageRomanticData", JSON.stringify(fetchdat2));
    romanticvalue(fetchdat2);  
    const fetchdat3 = await Make_A_Fetch_Request("Geans",['Action'],start,end);
    localStorage.setItem("HomePageActionData", JSON.stringify(fetchdat3));
    actionvalue(fetchdat3);  
    const fetchdat4 = await Make_A_Fetch_Request("Geans",['Comedy'],start,end);
    localStorage.setItem("HomePageComedyData", JSON.stringify(fetchdat4));
    comedyvalue(fetchdat4);   
    const fetchdat5 = await Make_A_Fetch_Request("Geans",['Crime'],start,end);
    localStorage.setItem("HomePageCrimeData", JSON.stringify(fetchdat3));
    crimevalue(fetchdat5);   
    const fetchdat6 = await Make_A_Fetch_Request("Geans",['Drama'],start,end);
    localStorage.setItem("HomePageDramaData", JSON.stringify(fetchdat6));
    dramavalue(fetchdat6);  
    const fetchdat7 = await Make_A_Fetch_Request("Geans",['Horror'],start,end);
    localStorage.setItem("HomePageHorrorData", JSON.stringify(fetchdat7));
    horrorvalue(fetchdat7);   
    const fetchdat8 = await Make_A_Fetch_Request("Geans",['Thriller'],start,end);
    localStorage.setItem("HomePageTraillerData", JSON.stringify(fetchdat8));
    trailerdata(fetchdat8);  
    const fetchdat9 = await Make_A_Fetch_Request("Geans",['Adventure'],start,end);
    localStorage.setItem("HomePageAdventureData", JSON.stringify(fetchdat9));
    adventurevalue(fetchdat9);  
    const fetchdat10 = await Make_A_Fetch_Request("MainCategory",['Adult'],start,end);
    localStorage.setItem("HomePageAdultData", JSON.stringify(fetchdat10));
    adultvalue(fetchdat10);
  }
  useEffect(()=>{
      bannersvalue(JSON.parse(localStorage.getItem("HomePageBanners")) || []);
      banner();
      recentuploadedvalue(JSON.parse(localStorage.getItem("HomePageRecentUpload")) || []);
      webseriesvalue(JSON.parse(localStorage.getItem("HomePageWebSeriesData")) || []);
      romanticvalue(JSON.parse(localStorage.getItem("HomePageRomanticData")) || []);
      actionvalue(JSON.parse(localStorage.getItem("HomePageActionData")) || []);
      comedyvalue(JSON.parse(localStorage.getItem("HomePageComedyData")) || []);
      crimevalue(JSON.parse(localStorage.getItem("HomePageCrimeData")) || []);
      dramavalue(JSON.parse(localStorage.getItem("HomePageDramaData")) || []);
      horrorvalue(JSON.parse(localStorage.getItem("HomePageHorrorData")) || []);
      trailerdata(JSON.parse(localStorage.getItem("HomePageTraillerData")) || []);
      adventurevalue(JSON.parse(localStorage.getItem("HomePageAdventureData")) || []);
      adultvalue(JSON.parse(localStorage.getItem("HomePageAdultData")) || []);
      data();
  },[])
  return (
    <>
      <Head>
        <title>Free Netflix :- Watch All New Movies and Shows For Free or Download in HD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Image className='fixed z-0 w-screen' src={banners.Big_Image} alt='banner' width={3000} height={3000} />
      <div className="z-1 relative">
        <MainBanners banners={banners}/>
        <div className='divshadow'>
          <div>
              {recentuploaded.length !== 0?<Slider data={recentuploaded} text="Recent Uploaded ..." link={"HomePageRecentUpload"}/>:<EmptySlider text="Recent Uploaded ..."/>}
              {webseries.length !== 0?<Slider data={webseries} text="Web Series ..." link={"HomePageWebSeriesData"}/>:<EmptySlider text="Web Series ..."/>}
              {romantic.length !== 0?<Slider data={romantic} text="Romantic ..." link={"HomePageRomanticData"}/>:<EmptySlider text="Romantic ..."/>}
              {action.length !== 0?<Slider data={action} text="Action ..." link={"HomePageActionData"}/>:<EmptySlider text="Action ..."/>}
              {comedy.length !== 0?<Slider data={comedy} text="Comedy ..." link={"HomePageComedyData"}/>:<EmptySlider text="Comedy ..."/>}
              {crime.length !== 0?<Slider data={crime} text="Crime ..." link={"HomePageCrimeData"}/>:<EmptySlider text="Crime ..."/>}
              {drame.length !== 0?<Slider data={drame} text="Drama ..." link={"HomePageDramaData"}/>:<EmptySlider text="Drama ..."/>}
              {horror.length !== 0?<Slider data={horror} text="Horror ..." link={"HomePageHorrorData"}/>:<EmptySlider text="Horror ..."/>}
              {trailer.length !== 0?<Slider data={trailer} text="Trailler ..." link={"HomePageTraillerData"}/>:<EmptySlider text="Trailler ..."/>}
              {adventure.length !== 0?<Slider data={adventure} text="Adventure ..." link={"HomePageAdventureData"}/>:<EmptySlider text="Adventure ..."/>}
              {adult.length !== 0?<Slider data={adult} text="Adult ..." link={"HomePageAdultData"}/>:<EmptySlider text="Adult ..."/>}
          </div>
        </div>
      </div>
    </>
  )
}
