import Head from 'next/head'
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useState, useEffect } from 'react';
import { createClient } from "@supabase/supabase-js";
export default function Player() {
  const [ID,IDvalue] = useState(null);
  const [FileID,FileIDvalue] = useState(null);
  const [iframe,iframevalue] = useState(null);
  const [video,videodata] = useState([]);
  const router = useRouter();
  const { player } = router.query;
  const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_KEY);
  const banner = async ()=>{
    let Arrdata = await supabase.from('Free-Netflix-Darabase').select('*').eq('ID',player[0]);
    if(Arrdata.data){
      videodata(Arrdata.data[0]);
      if(Arrdata.data[0].Plateform === "filemoon"){
        iframevalue(`https://filemoon.sx/e/${Arrdata.data[0].FileID}`);
      }
      else if(Arrdata.data[0].Plateform === "Youtube"){
        iframevalue(`https://www.youtube.com/embed/${Arrdata.data[0].FileID}`);
      }
    }
  }
  useEffect(()=>{
    if(player !== undefined){
      IDvalue(player[0]);
      FileIDvalue(player[1]);
      banner();
    }},[player])
  return (
    <>
          <Head>
            <title>Player :- {video.Title}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/logo.png" />
          </Head>
        {FileID&&ID&&video&&iframe?
          <>
            <div id='div1'>
              <iframe className="w-full h-full absolute top-0 left-0" src={iframe}></iframe>
            </div>
          </>:<></>
        }
    </>
  );
}