import Head from 'next/head'
import { useRouter } from 'next/router';
import { useState, useEffect } from 'react';
import { createClient } from "@supabase/supabase-js";
export default function Player() {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_KEY);
  const [iframe,iframevalue] = useState(null);
  const [video,videodata] = useState([]);
  const [image,imagevalue] = useState([]);
  const router = useRouter();
  const { player } = router.query;
  const banner = async ()=>{
    let Arrdata = await supabase.from('Free-Netflix-Darabase').select('*').eq('ID',player[0]);
    if(Arrdata.data){
      videodata(Arrdata.data[0]);
      imagevalue(Arrdata.data[0].Image);
      if(Arrdata.data[0].Plateform === "filemoon"){
        iframevalue(`https://filemoon.sx/e/${Arrdata.data[0].FileID}?poster=${Arrdata.data[0].Image}`);
      }
      else if(Arrdata.data[0].Plateform === "Youtube"){
        iframevalue(`https://www.youtube.com/embed/${Arrdata.data[0].FileID}`);
      }
    }
  }
  const foryoutube = async()=>{
    let Arrdata = await supabase.from('Free-Netflix-Songs').select('*').eq('id',player[1]);
    if(Arrdata.data){
      videodata(Arrdata.data[0]);
      imagevalue(Arrdata.data[0].image);
      iframevalue(`https://www.youtube.com/embed/${Arrdata.data[0].fileid}`);
    }
  }
  useEffect(()=>{
    if(player !== undefined){
      if(player[1] ===undefined){
        banner();
      }
      else{
        foryoutube();
      }
    }},[player])
  return (
    <>
          <Head>
            <title>Player :- {video.Title}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/logo.png" />
          </Head>
        {video&&image&&iframe?
          <>
            <div id='div1' className='aspect-video rounded-lg'>
              <iframe frameborder="0" allowfullscreen="1" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" title="" width="100%" height="100%" src={iframe}></iframe>
            </div>
          </>:<><div id='div1' className='aspect-video rounded-lg'></div></>
        }
    </>
  );
}