import Head from 'next/head'
import Link from 'next/link';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useState, useEffect } from 'react';
import { createClient } from "@supabase/supabase-js";
import {Make_A_Fetch_Request} from '@/components/request/makerequest';
import ViewAllRender from '@/components/viewall/viewall';
import EmptyViewAllRender from '@/components/viewall/emptyviewall';
export default function Player() {
  const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_KEY);
  const [iframe,iframevalue] = useState(null);
  const [video,videodata] = useState([]);
  const [image,imagevalue] = useState([]);
  const [pagedata,pagedatavalue] = useState([])
  const router = useRouter();
  const { player } = router.query;
  const banner = async ()=>{
    let Arrdata = await supabase.from('Free-Netflix-Darabase').select('*').eq('ID',player[0]);
    if(Arrdata.data){
      videodata(Arrdata.data[0]);
      imagevalue(Arrdata.data[0].Image);
      if(Arrdata.data[0].Plateform === "filemoon"){
        iframevalue(`https://filemoon.sx/e/${Arrdata.data[0].FileID}?poster=${Arrdata.data[0].Image}`);
      }
      else if(Arrdata.data[0].Plateform === "Youtube"){
        iframevalue(`https://www.youtube.com/embed/${Arrdata.data[0].FileID}`);
      }
      const cat = Arrdata.data[0].Geans;
      const fetchdat = await Make_A_Fetch_Request("Geans",[cat],0,49);
      pagedatavalue(fetchdat);
    }
  }
  const foryoutube = async()=>{
    let Arrdata = await supabase.from('Free-Netflix-Songs').select('*').eq('id',player[1]);
    if(Arrdata.data){
      videodata(Arrdata.data[0]);
      imagevalue(Arrdata.data[0].image);
      iframevalue(`https://www.youtube.com/embed/${Arrdata.data[0].fileid}`);
      const fetchdat = await supabase.from('Free-Netflix-Darabase').select('*').in("Plateform",["Youtube"]).range(0,49);
      pagedatavalue(fetchdat.data);
    }
  }
  const user = async()=>{  
    const verifyuser = await supabase.auth.getUser();
    console.log(verifyuser.data.user);
  }
  useEffect(()=>{
    user();
    if(player !== undefined){
      if(player[1] ===undefined){
        banner();
      }
      else{
        foryoutube();
      }
    }},[player])
  return (
    <>
          <Head>
            <title>Player :- {video.Title} On Free Netflix</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/logo.png" />
          </Head>
        {video&&image&&iframe?
          <>
            <div id='div1' className='aspect-video rounded-lg'>
              <iframe frameborder="0" allowfullscreen="1" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" title="" width="100%" height="100%" src={iframe}></iframe>
            </div>
          </>:<><div id='div1' className='aspect-video rounded-lg'></div></>
        }
        <Link href="https://beta.publishers.adsterra.com/referral/aKMU588PJU"><Image alt="banner" style={{margin:"auto"}} src="https://landings-cdn.adsterratech.com/referralBanners/gif/720x90_adsterra_reff.gif" width={700} height={700} /></Link>
        <div id="container-0ad2289ea9e1e73bd2b5439c23a4fc36"></div>
        {pagedata.length !==0?<><ViewAllRender data={pagedata}/></>:<><EmptyViewAllRender/></>}
    </>
  );
}